services:
  app:
    build: .
    ports:
      - "24500:5000"
    env_file: .env
    # command: "uvicorn main:app --reload --host 0.0.0.0"
    restart: always
    tty: true
    volumes:
      - .:/app
